steps:
  - label: "Build and Upload Artifact"
    command: cd hello && go build -o ./my-hello-app
    key: "build-step"
    artifact_paths: "hello/my-hello-app"
  - label: "Get User Name"
    input: "Please input your name:"
    fields:
      - text: "Your Name"
        key: "name"
    key: "input-step"
    depends_on: ["build-step"]
  - label: "Execution"
    command: ".buildkite/execution.sh"
    key: "execution-step"
    depends_on: ["input-step"]
