steps:
  - label: "Build and Get Artifact"
    command: |
      cd hello 
      go build -o ./my-hello-app
    key: "build-step"
    artifact_paths: "hello/my-hello-app"

  - label: "Get Name Input"
    input: "Please input your name"
    fields:
      - text: "Your name"
        key: "name"
    key: "input-step"
    depends_on: ["build-step"]

  - label: "Execution"
    command: |
      .buildkite/execution.sh
    depends_on: ["input-step"]
